### ISSUE TITLE
As a user I want the provision highlighted in yellow briefly when I click on a legislation TOC link

### ISSUE THREAD

**Issue by longhotsummer** [africanlii/liiweb#133]
Add this CSS to the legislation SCSS file:

```css
@keyframes fadeout {
  from { background-color: yellow; }
  to { background-color: none; }
}

.akoma-ntoso :target {
  animation: fadeout 2s;
}
```
